env:
    CONFIG: config.shh
    CIRRUS_SHELL: bash

task:
  name: "CirrusCI-Recovery-Builder"
  timeout_in: 120m
  container:
      image: ubuntu:latest
      cpu: 4
      memory: 16G

  Sync_script:
      - sleep 10m
